replicaCount: 3

bookkeeper:
  replicas: 3
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  storage:
    ledgers:
      size: 100Gi
    journals:
      size: 20Gi

broker:
  replicas: 3
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "4"
      memory: "8Gi"

zookeeper:
  replicas: 3
  storage:
    size: 20Gi
